language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: sryoRkWiGLFoUcy4r2beR1seYoNUERkoexfQac2neW6JQufw9Nf0YgIenZWcsiZP+D3RCRpSJKyBUBKpla6k1a/LrNG4nzKhSVkMgTP1q+7I/PEbXcaduQeAHnYRgr+KDDt7zzQuxEw1aj9tT/KuySa0WWFA5S4t3mekLe0XbQq6/XhwxEIZSEUeIeLo8waN9ur3FKmONOLu7/Gl9/h1wiaKumSLRsuJbJkAlKlKMIcI4uzFkE6pk8yGV+ZbAxIArXPmkNGnSrhBMv3+DEzyf7ljUw+L/XFxNE2r3SwxqYsFs8w1bvKpOUwOpht0BIZoWt1sBIRCt8KCnIgAPIpsnF//LxTtOWQyJFGMf32X2u6CHYk7JotNhzswxYvRXZT/I4pLj7tdT2d/8aCCfWdr9n2fvTyqoaH2G+KbMaPxwfqtzROkYV/G5OnxctnHkEhzj7FG9myYairW1QRVm1ssN5p4qjFbQPzJhQ5OzKw3ngam+CjnHeOxq67u9Sd3jQyg+b8s7rkWxqZX8xnZKYGLYezvWMeijOnZaVbnm3Gfb5TYDIZ/gv47bk6XbC12eIPVi0UvPwGIJ091AkwxOZBNNSQoYH2CSojQym1aVjr5UdXVQ/6kqiZdwAqsCoFxvY0La9J5kk2gWpIySy7iQWy4ugAoc31IwoUUUOwiNn91+bM=
  app: tranquil-plains-63580
